### ISSUE TITLE
[BUG] pypet2bids collects additional values from spreadsheet that DNE; csv

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#227]
**Describe the bug**
Given the attached spreadsheet as input to the `-m` flag, pet2bids raises a flatten series error, it seems to collect two values from the csv where there should only be on, `n/a` in this example. However, it's returning a series containing `[0, 'n/a']` which is believed to create this error, see:

```
Traceback (most recent call last):
  File "/usr/local/bin/dcm2niix4pet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pypet2bids/dcm2niix4pet.py", line 1354, in main
    converter = Dcm2niix4PET(
  File "/usr/local/lib/python3.8/dist-packages/pypet2bids/dcm2niix4pet.py", line 471, in __init__
    helper_functions.single_spreadsheet_reader(
  File "/usr/local/lib/python3.8/dist-packages/pypet2bids/helper_functions.py", line 155, in single_spreadsheet_reader
    metadata[field] = flatten_series(series)
  File "/usr/local/lib/python3.8/dist-packages/pypet2bids/helper_functions.py", line 103, in flatten_series
    raise Exception(f"Invalid Series: {series}")
Exception: Invalid Series: 0   NaN
Name: SpecificRadioactivity, dtype: float64
```
[pet_metadata.csv](https://github.com/openneuropet/PET2BIDS/files/12729169/pet_metadata.csv)

**Expected behaviour**
Reading in the attached spreadsheet should yield a specific radioactivity of `n/a`.

**Desktop (please complete the following information):**
 - Version (matlab/python)

**Comment by dlevitas** [comment]
I may be mis-reading the [BIDS-specification for PET data](https://github.com/bids-standard/bids-specification/blob/f6bcb0a147effefc7bdc72622d885fbd53ee6310/src/schema/objects/metadata.yaml#L3208), but for these metadata fields, it appears that `"n/a"` is acceptable and even should be entered, assuming it isn't an FDG sequence.

**Comment by bendhouseart** [comment]
Yes, "n/a" is accepted as often the data simply isn't available. We'd rather people share what they have then give up entirely.

**Comment by bendhouseart** [comment]
@dlevitas closing this as I believe it was fixed some time ago, just not closed. Let me know if otherwise.
